/*
 * frame_params.h
 *
 *  Created on: 8 may. 2026
 *      Author: pablo
 */

#ifndef SRC_FRAME_PARAMS_H_
#define SRC_FRAME_PARAMS_H_

// Parámetros del frame de video (color)
#define VIDEO_FRAME_WIDTH_PIXELS   640
#define VIDEO_FRAME_HEIGHT_PIXELS  480
#define VIDEO_BYTES_PER_PIXEL      3
#define VIDEO_STRIDE_BYTES         (VIDEO_FRAME_WIDTH_PIXELS * VIDEO_BYTES_PER_PIXEL)
#define VIDEO_FRAME_SIZE_BYTES     (VIDEO_FRAME_WIDTH_PIXELS * VIDEO_FRAME_HEIGHT_PIXELS * VIDEO_BYTES_PER_PIXEL)

// Parámetros del frame de video (blanco y negro)
#define VIDEO_GRAY_FRAME_WIDTH_PIXELS   640
#define VIDEO_GRAY_FRAME_HEIGHT_PIXELS  480
#define VIDEO_GRAY_BYTES_PER_PIXEL      1
#define VIDEO_GRAY_STRIDE_BYTES         (VIDEO_GRAY_FRAME_WIDTH_PIXELS * VIDEO_GRAY_BYTES_PER_PIXEL)
#define VIDEO_GRAY_FRAME_SIZE_BYTES     (VIDEO_GRAY_FRAME_WIDTH_PIXELS * VIDEO_GRAY_FRAME_HEIGHT_PIXELS * VIDEO_GRAY_BYTES_PER_PIXEL)

#endif /* SRC_FRAME_PARAMS_H_ */
