// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="rgb2gray,hls_ip_2019_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010-clg400-1,HLS_INPUT_CLOCK=6.500000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.380000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=2,HLS_SYN_FF=762,HLS_SYN_LUT=948,HLS_VERSION=2019_1}" *)

module rgb2gray (
        ap_clk,
        ap_rst_n,
        src_axi_TDATA,
        src_axi_TVALID,
        src_axi_TREADY,
        src_axi_TKEEP,
        src_axi_TSTRB,
        src_axi_TUSER,
        src_axi_TLAST,
        src_axi_TID,
        src_axi_TDEST,
        dst_gray_axi_TDATA,
        dst_gray_axi_TVALID,
        dst_gray_axi_TREADY,
        dst_gray_axi_TKEEP,
        dst_gray_axi_TSTRB,
        dst_gray_axi_TUSER,
        dst_gray_axi_TLAST,
        dst_gray_axi_TID,
        dst_gray_axi_TDEST,
        s_axi_CTRL_AWVALID,
        s_axi_CTRL_AWREADY,
        s_axi_CTRL_AWADDR,
        s_axi_CTRL_WVALID,
        s_axi_CTRL_WREADY,
        s_axi_CTRL_WDATA,
        s_axi_CTRL_WSTRB,
        s_axi_CTRL_ARVALID,
        s_axi_CTRL_ARREADY,
        s_axi_CTRL_ARADDR,
        s_axi_CTRL_RVALID,
        s_axi_CTRL_RREADY,
        s_axi_CTRL_RDATA,
        s_axi_CTRL_RRESP,
        s_axi_CTRL_BVALID,
        s_axi_CTRL_BREADY,
        s_axi_CTRL_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_pp1_stage0 = 6'd16;
parameter    ap_ST_fsm_state10 = 6'd32;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 4;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [23:0] src_axi_TDATA;
input   src_axi_TVALID;
output   src_axi_TREADY;
input  [2:0] src_axi_TKEEP;
input  [2:0] src_axi_TSTRB;
input  [0:0] src_axi_TUSER;
input  [0:0] src_axi_TLAST;
input  [0:0] src_axi_TID;
input  [0:0] src_axi_TDEST;
output  [7:0] dst_gray_axi_TDATA;
output   dst_gray_axi_TVALID;
input   dst_gray_axi_TREADY;
output  [0:0] dst_gray_axi_TKEEP;
output  [0:0] dst_gray_axi_TSTRB;
output  [0:0] dst_gray_axi_TUSER;
output  [0:0] dst_gray_axi_TLAST;
output  [0:0] dst_gray_axi_TID;
output  [0:0] dst_gray_axi_TDEST;
input   s_axi_CTRL_AWVALID;
output   s_axi_CTRL_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_AWADDR;
input   s_axi_CTRL_WVALID;
output   s_axi_CTRL_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_CTRL_WSTRB;
input   s_axi_CTRL_ARVALID;
output   s_axi_CTRL_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_ARADDR;
output   s_axi_CTRL_RVALID;
input   s_axi_CTRL_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_RDATA;
output  [1:0] s_axi_CTRL_RRESP;
output   s_axi_CTRL_BVALID;
input   s_axi_CTRL_BREADY;
output  [1:0] s_axi_CTRL_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
reg   [23:0] src_axi_V_data_V_0_data_out;
wire    src_axi_V_data_V_0_vld_in;
wire    src_axi_V_data_V_0_vld_out;
wire    src_axi_V_data_V_0_ack_in;
reg    src_axi_V_data_V_0_ack_out;
reg   [23:0] src_axi_V_data_V_0_payload_A;
reg   [23:0] src_axi_V_data_V_0_payload_B;
reg    src_axi_V_data_V_0_sel_rd;
reg    src_axi_V_data_V_0_sel_wr;
wire    src_axi_V_data_V_0_sel;
wire    src_axi_V_data_V_0_load_A;
wire    src_axi_V_data_V_0_load_B;
reg   [1:0] src_axi_V_data_V_0_state;
wire    src_axi_V_data_V_0_state_cmp_full;
reg   [0:0] src_axi_V_user_V_0_data_out;
wire    src_axi_V_user_V_0_vld_in;
wire    src_axi_V_user_V_0_vld_out;
wire    src_axi_V_user_V_0_ack_in;
reg    src_axi_V_user_V_0_ack_out;
reg   [0:0] src_axi_V_user_V_0_payload_A;
reg   [0:0] src_axi_V_user_V_0_payload_B;
reg    src_axi_V_user_V_0_sel_rd;
reg    src_axi_V_user_V_0_sel_wr;
wire    src_axi_V_user_V_0_sel;
wire    src_axi_V_user_V_0_load_A;
wire    src_axi_V_user_V_0_load_B;
reg   [1:0] src_axi_V_user_V_0_state;
wire    src_axi_V_user_V_0_state_cmp_full;
reg   [0:0] src_axi_V_last_V_0_data_out;
wire    src_axi_V_last_V_0_vld_in;
wire    src_axi_V_last_V_0_vld_out;
wire    src_axi_V_last_V_0_ack_in;
reg    src_axi_V_last_V_0_ack_out;
reg   [0:0] src_axi_V_last_V_0_payload_A;
reg   [0:0] src_axi_V_last_V_0_payload_B;
reg    src_axi_V_last_V_0_sel_rd;
reg    src_axi_V_last_V_0_sel_wr;
wire    src_axi_V_last_V_0_sel;
wire    src_axi_V_last_V_0_load_A;
wire    src_axi_V_last_V_0_load_B;
reg   [1:0] src_axi_V_last_V_0_state;
wire    src_axi_V_last_V_0_state_cmp_full;
wire    src_axi_V_dest_V_0_vld_in;
reg    src_axi_V_dest_V_0_ack_out;
reg   [1:0] src_axi_V_dest_V_0_state;
reg   [7:0] dst_gray_axi_V_data_V_1_data_out;
reg    dst_gray_axi_V_data_V_1_vld_in;
wire    dst_gray_axi_V_data_V_1_vld_out;
wire    dst_gray_axi_V_data_V_1_ack_in;
wire    dst_gray_axi_V_data_V_1_ack_out;
reg   [7:0] dst_gray_axi_V_data_V_1_payload_A;
reg   [7:0] dst_gray_axi_V_data_V_1_payload_B;
reg    dst_gray_axi_V_data_V_1_sel_rd;
reg    dst_gray_axi_V_data_V_1_sel_wr;
wire    dst_gray_axi_V_data_V_1_sel;
wire    dst_gray_axi_V_data_V_1_load_A;
wire    dst_gray_axi_V_data_V_1_load_B;
reg   [1:0] dst_gray_axi_V_data_V_1_state;
wire    dst_gray_axi_V_data_V_1_state_cmp_full;
wire   [0:0] dst_gray_axi_V_keep_V_1_data_out;
reg    dst_gray_axi_V_keep_V_1_vld_in;
wire    dst_gray_axi_V_keep_V_1_vld_out;
wire    dst_gray_axi_V_keep_V_1_ack_out;
reg    dst_gray_axi_V_keep_V_1_sel_rd;
wire    dst_gray_axi_V_keep_V_1_sel;
reg   [1:0] dst_gray_axi_V_keep_V_1_state;
wire   [0:0] dst_gray_axi_V_strb_V_1_data_out;
reg    dst_gray_axi_V_strb_V_1_vld_in;
wire    dst_gray_axi_V_strb_V_1_vld_out;
wire    dst_gray_axi_V_strb_V_1_ack_out;
reg    dst_gray_axi_V_strb_V_1_sel_rd;
wire    dst_gray_axi_V_strb_V_1_sel;
reg   [1:0] dst_gray_axi_V_strb_V_1_state;
reg   [0:0] dst_gray_axi_V_user_V_1_data_out;
reg    dst_gray_axi_V_user_V_1_vld_in;
wire    dst_gray_axi_V_user_V_1_vld_out;
wire    dst_gray_axi_V_user_V_1_ack_in;
wire    dst_gray_axi_V_user_V_1_ack_out;
reg   [0:0] dst_gray_axi_V_user_V_1_payload_A;
reg   [0:0] dst_gray_axi_V_user_V_1_payload_B;
reg    dst_gray_axi_V_user_V_1_sel_rd;
reg    dst_gray_axi_V_user_V_1_sel_wr;
wire    dst_gray_axi_V_user_V_1_sel;
wire    dst_gray_axi_V_user_V_1_load_A;
wire    dst_gray_axi_V_user_V_1_load_B;
reg   [1:0] dst_gray_axi_V_user_V_1_state;
wire    dst_gray_axi_V_user_V_1_state_cmp_full;
reg   [0:0] dst_gray_axi_V_last_V_1_data_out;
reg    dst_gray_axi_V_last_V_1_vld_in;
wire    dst_gray_axi_V_last_V_1_vld_out;
wire    dst_gray_axi_V_last_V_1_ack_in;
wire    dst_gray_axi_V_last_V_1_ack_out;
reg   [0:0] dst_gray_axi_V_last_V_1_payload_A;
reg   [0:0] dst_gray_axi_V_last_V_1_payload_B;
reg    dst_gray_axi_V_last_V_1_sel_rd;
reg    dst_gray_axi_V_last_V_1_sel_wr;
wire    dst_gray_axi_V_last_V_1_sel;
wire    dst_gray_axi_V_last_V_1_load_A;
wire    dst_gray_axi_V_last_V_1_load_B;
reg   [1:0] dst_gray_axi_V_last_V_1_state;
wire    dst_gray_axi_V_last_V_1_state_cmp_full;
wire   [0:0] dst_gray_axi_V_id_V_1_data_out;
reg    dst_gray_axi_V_id_V_1_vld_in;
wire    dst_gray_axi_V_id_V_1_vld_out;
wire    dst_gray_axi_V_id_V_1_ack_out;
reg    dst_gray_axi_V_id_V_1_sel_rd;
wire    dst_gray_axi_V_id_V_1_sel;
reg   [1:0] dst_gray_axi_V_id_V_1_state;
wire   [0:0] dst_gray_axi_V_dest_V_1_data_out;
reg    dst_gray_axi_V_dest_V_1_vld_in;
wire    dst_gray_axi_V_dest_V_1_vld_out;
wire    dst_gray_axi_V_dest_V_1_ack_out;
reg    dst_gray_axi_V_dest_V_1_sel_rd;
wire    dst_gray_axi_V_dest_V_1_sel;
reg   [1:0] dst_gray_axi_V_dest_V_1_state;
reg    src_axi_TDATA_blk_n;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_pp1_stage0;
reg    ap_enable_reg_pp1_iter0;
wire    ap_block_pp1_stage0;
wire   [0:0] icmp_ln24_fu_359_p2;
wire   [0:0] icmp_ln29_fu_397_p2;
reg    dst_gray_axi_TDATA_blk_n;
reg    ap_enable_reg_pp1_iter3;
reg   [0:0] icmp_ln24_reg_505;
reg   [0:0] icmp_ln24_reg_505_pp1_iter2_reg;
reg    ap_enable_reg_pp1_iter4;
reg   [0:0] icmp_ln24_reg_505_pp1_iter3_reg;
reg   [0:0] pixel_in_last_V_1_reg_211;
reg   [23:0] pixel_in_data_V_1_reg_222;
reg   [0:0] pixel_in_3_1_reg_233;
reg   [9:0] c_idx_0_reg_244;
reg   [0:0] pixel_gray_out_last_s_reg_255;
reg   [0:0] pixel_gray_out_last_s_reg_255_pp1_iter1_reg;
reg    ap_predicate_op65_read_state5;
reg    ap_block_state5_pp1_stage0_iter0;
wire    ap_block_state6_pp1_stage0_iter1;
wire    ap_block_state7_pp1_stage0_iter2;
wire    ap_block_state8_pp1_stage0_iter3;
reg    ap_block_state8_io;
wire    ap_block_state9_pp1_stage0_iter4;
reg    ap_block_state9_io;
reg    ap_block_pp1_stage0_11001;
reg   [0:0] pixel_gray_out_last_s_reg_255_pp1_iter2_reg;
reg   [23:0] p_Val2_s_reg_268;
reg   [23:0] p_Val2_s_reg_268_pp1_iter1_reg;
reg   [23:0] p_Val2_s_reg_268_pp1_iter2_reg;
reg   [0:0] pixel_gray_out_user_s_reg_280;
reg   [0:0] pixel_gray_out_user_s_reg_280_pp1_iter1_reg;
reg   [0:0] pixel_gray_out_user_s_reg_280_pp1_iter2_reg;
reg   [23:0] tmp_data_V_1_reg_483;
reg   [0:0] tmp_last_V_1_reg_491;
wire   [0:0] icmp_ln22_fu_347_p2;
wire    ap_CS_fsm_state4;
reg    ap_block_state4;
wire   [8:0] r_idx_fu_353_p2;
reg   [8:0] r_idx_reg_500;
reg   [0:0] icmp_ln24_reg_505_pp1_iter1_reg;
wire   [9:0] c_idx_fu_365_p2;
wire   [7:0] bit_7_0_V_fu_403_p1;
reg   [7:0] bit_7_0_V_reg_518;
reg   [7:0] bit_7_0_V_reg_518_pp1_iter1_reg;
reg   [7:0] bit_15_8_V_reg_523;
reg   [7:0] bit_15_8_V_reg_523_pp1_iter1_reg;
reg   [7:0] bit_15_8_V_reg_523_pp1_iter2_reg;
reg   [7:0] bit_23_16_V_reg_528;
wire   [0:0] and_ln62_fu_433_p2;
reg   [0:0] and_ln62_reg_533;
reg   [0:0] and_ln62_reg_533_pp1_iter1_reg;
reg   [0:0] and_ln62_reg_533_pp1_iter2_reg;
wire   [14:0] mul_ln214_fu_442_p2;
reg   [14:0] mul_ln214_reg_537;
wire   [14:0] grp_fu_467_p3;
reg   [14:0] add_ln214_reg_542;
reg    ap_enable_reg_pp1_iter2;
reg    ap_block_pp1_stage0_subdone;
reg    ap_predicate_tran9to10_state5;
reg    ap_enable_reg_pp1_iter1;
reg   [0:0] pixel_in_last_V_0_reg_167;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state3;
reg   [23:0] pixel_in_data_V_0_reg_177;
reg   [0:0] pixel_in_3_0_reg_187;
reg   [8:0] r_idx_0_reg_199;
reg   [0:0] ap_phi_mux_pixel_in_last_V_1_phi_fu_214_p4;
reg   [23:0] ap_phi_mux_pixel_in_data_V_1_phi_fu_225_p4;
reg   [0:0] ap_phi_mux_pixel_in_3_1_phi_fu_236_p4;
reg   [0:0] ap_phi_mux_pixel_gray_out_last_s_phi_fu_260_p4;
wire   [0:0] ap_phi_reg_pp1_iter0_pixel_gray_out_last_s_reg_255;
reg   [23:0] ap_phi_mux_p_Val2_s_phi_fu_272_p4;
wire   [23:0] ap_phi_reg_pp1_iter0_p_Val2_s_reg_268;
wire   [0:0] ap_phi_reg_pp1_iter0_pixel_gray_out_user_s_reg_280;
wire   [0:0] grp_fu_337_p1;
reg   [0:0] pixel_in_last_V_3_reg_293;
reg   [23:0] pixel_in_data_V_3_reg_306;
reg   [0:0] pixel_in_3_3_reg_319;
reg    ap_block_pp1_stage0_01001;
wire   [8:0] trunc_ln29_fu_371_p1;
wire   [0:0] tmp_3_fu_381_p3;
wire   [8:0] or_ln29_fu_375_p2;
wire   [9:0] or_ln_fu_389_p3;
wire   [0:0] icmp_ln62_fu_427_p2;
wire   [7:0] mul_ln214_fu_442_p1;
wire   [15:0] grp_fu_474_p3;
wire   [5:0] grp_fu_467_p0;
wire   [7:0] grp_fu_467_p1;
wire   [8:0] grp_fu_474_p0;
wire   [7:0] grp_fu_474_p1;
wire   [14:0] grp_fu_474_p2;
reg   [5:0] ap_NS_fsm;
reg    ap_idle_pp1;
wire    ap_enable_pp1;
wire   [13:0] grp_fu_467_p10;
wire   [15:0] grp_fu_474_p10;
wire   [15:0] grp_fu_474_p20;
wire   [14:0] mul_ln214_fu_442_p10;
reg    ap_condition_1294;
reg    ap_condition_1003;
reg    ap_condition_1299;
reg    ap_condition_1303;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 src_axi_V_data_V_0_sel_rd = 1'b0;
#0 src_axi_V_data_V_0_sel_wr = 1'b0;
#0 src_axi_V_data_V_0_state = 2'd0;
#0 src_axi_V_user_V_0_sel_rd = 1'b0;
#0 src_axi_V_user_V_0_sel_wr = 1'b0;
#0 src_axi_V_user_V_0_state = 2'd0;
#0 src_axi_V_last_V_0_sel_rd = 1'b0;
#0 src_axi_V_last_V_0_sel_wr = 1'b0;
#0 src_axi_V_last_V_0_state = 2'd0;
#0 src_axi_V_dest_V_0_state = 2'd0;
#0 dst_gray_axi_V_data_V_1_sel_rd = 1'b0;
#0 dst_gray_axi_V_data_V_1_sel_wr = 1'b0;
#0 dst_gray_axi_V_data_V_1_state = 2'd0;
#0 dst_gray_axi_V_keep_V_1_sel_rd = 1'b0;
#0 dst_gray_axi_V_keep_V_1_state = 2'd0;
#0 dst_gray_axi_V_strb_V_1_sel_rd = 1'b0;
#0 dst_gray_axi_V_strb_V_1_state = 2'd0;
#0 dst_gray_axi_V_user_V_1_sel_rd = 1'b0;
#0 dst_gray_axi_V_user_V_1_sel_wr = 1'b0;
#0 dst_gray_axi_V_user_V_1_state = 2'd0;
#0 dst_gray_axi_V_last_V_1_sel_rd = 1'b0;
#0 dst_gray_axi_V_last_V_1_sel_wr = 1'b0;
#0 dst_gray_axi_V_last_V_1_state = 2'd0;
#0 dst_gray_axi_V_id_V_1_sel_rd = 1'b0;
#0 dst_gray_axi_V_id_V_1_state = 2'd0;
#0 dst_gray_axi_V_dest_V_1_sel_rd = 1'b0;
#0 dst_gray_axi_V_dest_V_1_state = 2'd0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter3 = 1'b0;
#0 ap_enable_reg_pp1_iter4 = 1'b0;
#0 ap_enable_reg_pp1_iter2 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
end

rgb2gray_CTRL_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
rgb2gray_CTRL_s_axi_U(
    .AWVALID(s_axi_CTRL_AWVALID),
    .AWREADY(s_axi_CTRL_AWREADY),
    .AWADDR(s_axi_CTRL_AWADDR),
    .WVALID(s_axi_CTRL_WVALID),
    .WREADY(s_axi_CTRL_WREADY),
    .WDATA(s_axi_CTRL_WDATA),
    .WSTRB(s_axi_CTRL_WSTRB),
    .ARVALID(s_axi_CTRL_ARVALID),
    .ARREADY(s_axi_CTRL_ARREADY),
    .ARADDR(s_axi_CTRL_ARADDR),
    .RVALID(s_axi_CTRL_RVALID),
    .RREADY(s_axi_CTRL_RREADY),
    .RDATA(s_axi_CTRL_RDATA),
    .RRESP(s_axi_CTRL_RRESP),
    .BVALID(s_axi_CTRL_BVALID),
    .BREADY(s_axi_CTRL_BREADY),
    .BRESP(s_axi_CTRL_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

rgb2gray_mac_mulabkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 15 ),
    .dout_WIDTH( 15 ))
rgb2gray_mac_mulabkb_U1(
    .din0(grp_fu_467_p0),
    .din1(grp_fu_467_p1),
    .din2(mul_ln214_reg_537),
    .dout(grp_fu_467_p3)
);

rgb2gray_mac_mulacud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 15 ),
    .dout_WIDTH( 16 ))
rgb2gray_mac_mulacud_U2(
    .din0(grp_fu_474_p0),
    .din1(grp_fu_474_p1),
    .din2(grp_fu_474_p2),
    .dout(grp_fu_474_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((ap_predicate_tran9to10_state5 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_subdone))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if ((~((dst_gray_axi_V_dest_V_1_state == 2'd1) | (dst_gray_axi_V_id_V_1_state == 2'd1) | (dst_gray_axi_V_last_V_1_state == 2'd1) | (dst_gray_axi_V_user_V_1_state == 2'd1) | (dst_gray_axi_V_strb_V_1_state == 2'd1) | (dst_gray_axi_V_keep_V_1_state == 2'd1) | (dst_gray_axi_V_data_V_1_state == 2'd1) | ((dst_gray_axi_V_dest_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_id_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_last_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_user_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_strb_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_keep_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_data_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0))) & (icmp_ln22_fu_347_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter2 <= ap_enable_reg_pp1_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter3 <= ap_enable_reg_pp1_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter4 <= ap_enable_reg_pp1_iter3;
        end else if ((~((dst_gray_axi_V_dest_V_1_state == 2'd1) | (dst_gray_axi_V_id_V_1_state == 2'd1) | (dst_gray_axi_V_last_V_1_state == 2'd1) | (dst_gray_axi_V_user_V_1_state == 2'd1) | (dst_gray_axi_V_strb_V_1_state == 2'd1) | (dst_gray_axi_V_keep_V_1_state == 2'd1) | (dst_gray_axi_V_data_V_1_state == 2'd1) | ((dst_gray_axi_V_dest_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_id_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_last_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_user_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_strb_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_keep_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_data_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0))) & (icmp_ln22_fu_347_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_enable_reg_pp1_iter4 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        dst_gray_axi_V_data_V_1_sel_rd <= 1'b0;
    end else begin
        if (((dst_gray_axi_V_data_V_1_ack_out == 1'b1) & (dst_gray_axi_V_data_V_1_vld_out == 1'b1))) begin
            dst_gray_axi_V_data_V_1_sel_rd <= ~dst_gray_axi_V_data_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        dst_gray_axi_V_data_V_1_sel_wr <= 1'b0;
    end else begin
        if (((dst_gray_axi_V_data_V_1_ack_in == 1'b1) & (dst_gray_axi_V_data_V_1_vld_in == 1'b1))) begin
            dst_gray_axi_V_data_V_1_sel_wr <= ~dst_gray_axi_V_data_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        dst_gray_axi_V_data_V_1_state <= 2'd0;
    end else begin
        if ((((dst_gray_axi_V_data_V_1_state == 2'd2) & (dst_gray_axi_V_data_V_1_vld_in == 1'b0)) | ((dst_gray_axi_V_data_V_1_state == 2'd3) & (dst_gray_axi_V_data_V_1_vld_in == 1'b0) & (dst_gray_axi_V_data_V_1_ack_out == 1'b1)))) begin
            dst_gray_axi_V_data_V_1_state <= 2'd2;
        end else if ((((dst_gray_axi_V_data_V_1_state == 2'd1) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_data_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0) & (dst_gray_axi_V_data_V_1_vld_in == 1'b1)))) begin
            dst_gray_axi_V_data_V_1_state <= 2'd1;
        end else if (((~((dst_gray_axi_V_data_V_1_vld_in == 1'b0) & (dst_gray_axi_V_data_V_1_ack_out == 1'b1)) & ~((dst_gray_axi_TREADY == 1'b0) & (dst_gray_axi_V_data_V_1_vld_in == 1'b1)) & (dst_gray_axi_V_data_V_1_state == 2'd3)) | ((dst_gray_axi_V_data_V_1_state == 2'd1) & (dst_gray_axi_V_data_V_1_ack_out == 1'b1)) | ((dst_gray_axi_V_data_V_1_state == 2'd2) & (dst_gray_axi_V_data_V_1_vld_in == 1'b1)))) begin
            dst_gray_axi_V_data_V_1_state <= 2'd3;
        end else begin
            dst_gray_axi_V_data_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        dst_gray_axi_V_dest_V_1_sel_rd <= 1'b0;
    end else begin
        if (((dst_gray_axi_V_dest_V_1_ack_out == 1'b1) & (dst_gray_axi_V_dest_V_1_vld_out == 1'b1))) begin
            dst_gray_axi_V_dest_V_1_sel_rd <= ~dst_gray_axi_V_dest_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        dst_gray_axi_V_dest_V_1_state <= 2'd0;
    end else begin
        if ((((dst_gray_axi_V_dest_V_1_state == 2'd2) & (dst_gray_axi_V_dest_V_1_vld_in == 1'b0)) | ((dst_gray_axi_V_dest_V_1_state == 2'd3) & (dst_gray_axi_V_dest_V_1_vld_in == 1'b0) & (dst_gray_axi_V_dest_V_1_ack_out == 1'b1)))) begin
            dst_gray_axi_V_dest_V_1_state <= 2'd2;
        end else if ((((dst_gray_axi_V_dest_V_1_state == 2'd1) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_dest_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0) & (dst_gray_axi_V_dest_V_1_vld_in == 1'b1)))) begin
            dst_gray_axi_V_dest_V_1_state <= 2'd1;
        end else if (((~((dst_gray_axi_V_dest_V_1_vld_in == 1'b0) & (dst_gray_axi_V_dest_V_1_ack_out == 1'b1)) & ~((dst_gray_axi_TREADY == 1'b0) & (dst_gray_axi_V_dest_V_1_vld_in == 1'b1)) & (dst_gray_axi_V_dest_V_1_state == 2'd3)) | ((dst_gray_axi_V_dest_V_1_state == 2'd1) & (dst_gray_axi_V_dest_V_1_ack_out == 1'b1)) | ((dst_gray_axi_V_dest_V_1_state == 2'd2) & (dst_gray_axi_V_dest_V_1_vld_in == 1'b1)))) begin
            dst_gray_axi_V_dest_V_1_state <= 2'd3;
        end else begin
            dst_gray_axi_V_dest_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        dst_gray_axi_V_id_V_1_sel_rd <= 1'b0;
    end else begin
        if (((dst_gray_axi_V_id_V_1_ack_out == 1'b1) & (dst_gray_axi_V_id_V_1_vld_out == 1'b1))) begin
            dst_gray_axi_V_id_V_1_sel_rd <= ~dst_gray_axi_V_id_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        dst_gray_axi_V_id_V_1_state <= 2'd0;
    end else begin
        if ((((dst_gray_axi_V_id_V_1_state == 2'd2) & (dst_gray_axi_V_id_V_1_vld_in == 1'b0)) | ((dst_gray_axi_V_id_V_1_state == 2'd3) & (dst_gray_axi_V_id_V_1_vld_in == 1'b0) & (dst_gray_axi_V_id_V_1_ack_out == 1'b1)))) begin
            dst_gray_axi_V_id_V_1_state <= 2'd2;
        end else if ((((dst_gray_axi_V_id_V_1_state == 2'd1) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_id_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0) & (dst_gray_axi_V_id_V_1_vld_in == 1'b1)))) begin
            dst_gray_axi_V_id_V_1_state <= 2'd1;
        end else if (((~((dst_gray_axi_V_id_V_1_vld_in == 1'b0) & (dst_gray_axi_V_id_V_1_ack_out == 1'b1)) & ~((dst_gray_axi_TREADY == 1'b0) & (dst_gray_axi_V_id_V_1_vld_in == 1'b1)) & (dst_gray_axi_V_id_V_1_state == 2'd3)) | ((dst_gray_axi_V_id_V_1_state == 2'd1) & (dst_gray_axi_V_id_V_1_ack_out == 1'b1)) | ((dst_gray_axi_V_id_V_1_state == 2'd2) & (dst_gray_axi_V_id_V_1_vld_in == 1'b1)))) begin
            dst_gray_axi_V_id_V_1_state <= 2'd3;
        end else begin
            dst_gray_axi_V_id_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        dst_gray_axi_V_keep_V_1_sel_rd <= 1'b0;
    end else begin
        if (((dst_gray_axi_V_keep_V_1_ack_out == 1'b1) & (dst_gray_axi_V_keep_V_1_vld_out == 1'b1))) begin
            dst_gray_axi_V_keep_V_1_sel_rd <= ~dst_gray_axi_V_keep_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        dst_gray_axi_V_keep_V_1_state <= 2'd0;
    end else begin
        if ((((dst_gray_axi_V_keep_V_1_state == 2'd2) & (dst_gray_axi_V_keep_V_1_vld_in == 1'b0)) | ((dst_gray_axi_V_keep_V_1_state == 2'd3) & (dst_gray_axi_V_keep_V_1_vld_in == 1'b0) & (dst_gray_axi_V_keep_V_1_ack_out == 1'b1)))) begin
            dst_gray_axi_V_keep_V_1_state <= 2'd2;
        end else if ((((dst_gray_axi_V_keep_V_1_state == 2'd1) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_keep_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0) & (dst_gray_axi_V_keep_V_1_vld_in == 1'b1)))) begin
            dst_gray_axi_V_keep_V_1_state <= 2'd1;
        end else if (((~((dst_gray_axi_V_keep_V_1_vld_in == 1'b0) & (dst_gray_axi_V_keep_V_1_ack_out == 1'b1)) & ~((dst_gray_axi_TREADY == 1'b0) & (dst_gray_axi_V_keep_V_1_vld_in == 1'b1)) & (dst_gray_axi_V_keep_V_1_state == 2'd3)) | ((dst_gray_axi_V_keep_V_1_state == 2'd1) & (dst_gray_axi_V_keep_V_1_ack_out == 1'b1)) | ((dst_gray_axi_V_keep_V_1_state == 2'd2) & (dst_gray_axi_V_keep_V_1_vld_in == 1'b1)))) begin
            dst_gray_axi_V_keep_V_1_state <= 2'd3;
        end else begin
            dst_gray_axi_V_keep_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        dst_gray_axi_V_last_V_1_sel_rd <= 1'b0;
    end else begin
        if (((dst_gray_axi_V_last_V_1_ack_out == 1'b1) & (dst_gray_axi_V_last_V_1_vld_out == 1'b1))) begin
            dst_gray_axi_V_last_V_1_sel_rd <= ~dst_gray_axi_V_last_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        dst_gray_axi_V_last_V_1_sel_wr <= 1'b0;
    end else begin
        if (((dst_gray_axi_V_last_V_1_ack_in == 1'b1) & (dst_gray_axi_V_last_V_1_vld_in == 1'b1))) begin
            dst_gray_axi_V_last_V_1_sel_wr <= ~dst_gray_axi_V_last_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        dst_gray_axi_V_last_V_1_state <= 2'd0;
    end else begin
        if ((((dst_gray_axi_V_last_V_1_state == 2'd2) & (dst_gray_axi_V_last_V_1_vld_in == 1'b0)) | ((dst_gray_axi_V_last_V_1_state == 2'd3) & (dst_gray_axi_V_last_V_1_vld_in == 1'b0) & (dst_gray_axi_V_last_V_1_ack_out == 1'b1)))) begin
            dst_gray_axi_V_last_V_1_state <= 2'd2;
        end else if ((((dst_gray_axi_V_last_V_1_state == 2'd1) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_last_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0) & (dst_gray_axi_V_last_V_1_vld_in == 1'b1)))) begin
            dst_gray_axi_V_last_V_1_state <= 2'd1;
        end else if (((~((dst_gray_axi_V_last_V_1_vld_in == 1'b0) & (dst_gray_axi_V_last_V_1_ack_out == 1'b1)) & ~((dst_gray_axi_TREADY == 1'b0) & (dst_gray_axi_V_last_V_1_vld_in == 1'b1)) & (dst_gray_axi_V_last_V_1_state == 2'd3)) | ((dst_gray_axi_V_last_V_1_state == 2'd1) & (dst_gray_axi_V_last_V_1_ack_out == 1'b1)) | ((dst_gray_axi_V_last_V_1_state == 2'd2) & (dst_gray_axi_V_last_V_1_vld_in == 1'b1)))) begin
            dst_gray_axi_V_last_V_1_state <= 2'd3;
        end else begin
            dst_gray_axi_V_last_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        dst_gray_axi_V_strb_V_1_sel_rd <= 1'b0;
    end else begin
        if (((dst_gray_axi_V_strb_V_1_ack_out == 1'b1) & (dst_gray_axi_V_strb_V_1_vld_out == 1'b1))) begin
            dst_gray_axi_V_strb_V_1_sel_rd <= ~dst_gray_axi_V_strb_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        dst_gray_axi_V_strb_V_1_state <= 2'd0;
    end else begin
        if ((((dst_gray_axi_V_strb_V_1_state == 2'd2) & (dst_gray_axi_V_strb_V_1_vld_in == 1'b0)) | ((dst_gray_axi_V_strb_V_1_state == 2'd3) & (dst_gray_axi_V_strb_V_1_vld_in == 1'b0) & (dst_gray_axi_V_strb_V_1_ack_out == 1'b1)))) begin
            dst_gray_axi_V_strb_V_1_state <= 2'd2;
        end else if ((((dst_gray_axi_V_strb_V_1_state == 2'd1) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_strb_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0) & (dst_gray_axi_V_strb_V_1_vld_in == 1'b1)))) begin
            dst_gray_axi_V_strb_V_1_state <= 2'd1;
        end else if (((~((dst_gray_axi_V_strb_V_1_vld_in == 1'b0) & (dst_gray_axi_V_strb_V_1_ack_out == 1'b1)) & ~((dst_gray_axi_TREADY == 1'b0) & (dst_gray_axi_V_strb_V_1_vld_in == 1'b1)) & (dst_gray_axi_V_strb_V_1_state == 2'd3)) | ((dst_gray_axi_V_strb_V_1_state == 2'd1) & (dst_gray_axi_V_strb_V_1_ack_out == 1'b1)) | ((dst_gray_axi_V_strb_V_1_state == 2'd2) & (dst_gray_axi_V_strb_V_1_vld_in == 1'b1)))) begin
            dst_gray_axi_V_strb_V_1_state <= 2'd3;
        end else begin
            dst_gray_axi_V_strb_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        dst_gray_axi_V_user_V_1_sel_rd <= 1'b0;
    end else begin
        if (((dst_gray_axi_V_user_V_1_ack_out == 1'b1) & (dst_gray_axi_V_user_V_1_vld_out == 1'b1))) begin
            dst_gray_axi_V_user_V_1_sel_rd <= ~dst_gray_axi_V_user_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        dst_gray_axi_V_user_V_1_sel_wr <= 1'b0;
    end else begin
        if (((dst_gray_axi_V_user_V_1_ack_in == 1'b1) & (dst_gray_axi_V_user_V_1_vld_in == 1'b1))) begin
            dst_gray_axi_V_user_V_1_sel_wr <= ~dst_gray_axi_V_user_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        dst_gray_axi_V_user_V_1_state <= 2'd0;
    end else begin
        if ((((dst_gray_axi_V_user_V_1_state == 2'd2) & (dst_gray_axi_V_user_V_1_vld_in == 1'b0)) | ((dst_gray_axi_V_user_V_1_state == 2'd3) & (dst_gray_axi_V_user_V_1_vld_in == 1'b0) & (dst_gray_axi_V_user_V_1_ack_out == 1'b1)))) begin
            dst_gray_axi_V_user_V_1_state <= 2'd2;
        end else if ((((dst_gray_axi_V_user_V_1_state == 2'd1) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_user_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0) & (dst_gray_axi_V_user_V_1_vld_in == 1'b1)))) begin
            dst_gray_axi_V_user_V_1_state <= 2'd1;
        end else if (((~((dst_gray_axi_V_user_V_1_vld_in == 1'b0) & (dst_gray_axi_V_user_V_1_ack_out == 1'b1)) & ~((dst_gray_axi_TREADY == 1'b0) & (dst_gray_axi_V_user_V_1_vld_in == 1'b1)) & (dst_gray_axi_V_user_V_1_state == 2'd3)) | ((dst_gray_axi_V_user_V_1_state == 2'd1) & (dst_gray_axi_V_user_V_1_ack_out == 1'b1)) | ((dst_gray_axi_V_user_V_1_state == 2'd2) & (dst_gray_axi_V_user_V_1_vld_in == 1'b1)))) begin
            dst_gray_axi_V_user_V_1_state <= 2'd3;
        end else begin
            dst_gray_axi_V_user_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        src_axi_V_data_V_0_sel_rd <= 1'b0;
    end else begin
        if (((src_axi_V_data_V_0_ack_out == 1'b1) & (src_axi_V_data_V_0_vld_out == 1'b1))) begin
            src_axi_V_data_V_0_sel_rd <= ~src_axi_V_data_V_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        src_axi_V_data_V_0_sel_wr <= 1'b0;
    end else begin
        if (((src_axi_V_data_V_0_ack_in == 1'b1) & (src_axi_V_data_V_0_vld_in == 1'b1))) begin
            src_axi_V_data_V_0_sel_wr <= ~src_axi_V_data_V_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        src_axi_V_data_V_0_state <= 2'd0;
    end else begin
        if ((((src_axi_V_data_V_0_state == 2'd2) & (src_axi_V_data_V_0_vld_in == 1'b0)) | ((src_axi_V_data_V_0_state == 2'd3) & (src_axi_V_data_V_0_vld_in == 1'b0) & (src_axi_V_data_V_0_ack_out == 1'b1)))) begin
            src_axi_V_data_V_0_state <= 2'd2;
        end else if ((((src_axi_V_data_V_0_state == 2'd1) & (src_axi_V_data_V_0_ack_out == 1'b0)) | ((src_axi_V_data_V_0_state == 2'd3) & (src_axi_V_data_V_0_ack_out == 1'b0) & (src_axi_V_data_V_0_vld_in == 1'b1)))) begin
            src_axi_V_data_V_0_state <= 2'd1;
        end else if (((~((src_axi_V_data_V_0_vld_in == 1'b0) & (src_axi_V_data_V_0_ack_out == 1'b1)) & ~((src_axi_V_data_V_0_ack_out == 1'b0) & (src_axi_V_data_V_0_vld_in == 1'b1)) & (src_axi_V_data_V_0_state == 2'd3)) | ((src_axi_V_data_V_0_state == 2'd1) & (src_axi_V_data_V_0_ack_out == 1'b1)) | ((src_axi_V_data_V_0_state == 2'd2) & (src_axi_V_data_V_0_vld_in == 1'b1)))) begin
            src_axi_V_data_V_0_state <= 2'd3;
        end else begin
            src_axi_V_data_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        src_axi_V_dest_V_0_state <= 2'd0;
    end else begin
        if ((((src_axi_V_dest_V_0_state == 2'd2) & (src_axi_V_dest_V_0_vld_in == 1'b0)) | ((src_axi_V_dest_V_0_state == 2'd3) & (src_axi_V_dest_V_0_vld_in == 1'b0) & (src_axi_V_dest_V_0_ack_out == 1'b1)))) begin
            src_axi_V_dest_V_0_state <= 2'd2;
        end else if ((((src_axi_V_dest_V_0_state == 2'd1) & (src_axi_V_dest_V_0_ack_out == 1'b0)) | ((src_axi_V_dest_V_0_state == 2'd3) & (src_axi_V_dest_V_0_ack_out == 1'b0) & (src_axi_V_dest_V_0_vld_in == 1'b1)))) begin
            src_axi_V_dest_V_0_state <= 2'd1;
        end else if (((~((src_axi_V_dest_V_0_vld_in == 1'b0) & (src_axi_V_dest_V_0_ack_out == 1'b1)) & ~((src_axi_V_dest_V_0_ack_out == 1'b0) & (src_axi_V_dest_V_0_vld_in == 1'b1)) & (src_axi_V_dest_V_0_state == 2'd3)) | ((src_axi_V_dest_V_0_state == 2'd1) & (src_axi_V_dest_V_0_ack_out == 1'b1)) | ((src_axi_V_dest_V_0_state == 2'd2) & (src_axi_V_dest_V_0_vld_in == 1'b1)))) begin
            src_axi_V_dest_V_0_state <= 2'd3;
        end else begin
            src_axi_V_dest_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        src_axi_V_last_V_0_sel_rd <= 1'b0;
    end else begin
        if (((src_axi_V_last_V_0_ack_out == 1'b1) & (src_axi_V_last_V_0_vld_out == 1'b1))) begin
            src_axi_V_last_V_0_sel_rd <= ~src_axi_V_last_V_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        src_axi_V_last_V_0_sel_wr <= 1'b0;
    end else begin
        if (((src_axi_V_last_V_0_ack_in == 1'b1) & (src_axi_V_last_V_0_vld_in == 1'b1))) begin
            src_axi_V_last_V_0_sel_wr <= ~src_axi_V_last_V_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        src_axi_V_last_V_0_state <= 2'd0;
    end else begin
        if ((((src_axi_V_last_V_0_state == 2'd2) & (src_axi_V_last_V_0_vld_in == 1'b0)) | ((src_axi_V_last_V_0_state == 2'd3) & (src_axi_V_last_V_0_vld_in == 1'b0) & (src_axi_V_last_V_0_ack_out == 1'b1)))) begin
            src_axi_V_last_V_0_state <= 2'd2;
        end else if ((((src_axi_V_last_V_0_state == 2'd1) & (src_axi_V_last_V_0_ack_out == 1'b0)) | ((src_axi_V_last_V_0_state == 2'd3) & (src_axi_V_last_V_0_ack_out == 1'b0) & (src_axi_V_last_V_0_vld_in == 1'b1)))) begin
            src_axi_V_last_V_0_state <= 2'd1;
        end else if (((~((src_axi_V_last_V_0_vld_in == 1'b0) & (src_axi_V_last_V_0_ack_out == 1'b1)) & ~((src_axi_V_last_V_0_ack_out == 1'b0) & (src_axi_V_last_V_0_vld_in == 1'b1)) & (src_axi_V_last_V_0_state == 2'd3)) | ((src_axi_V_last_V_0_state == 2'd1) & (src_axi_V_last_V_0_ack_out == 1'b1)) | ((src_axi_V_last_V_0_state == 2'd2) & (src_axi_V_last_V_0_vld_in == 1'b1)))) begin
            src_axi_V_last_V_0_state <= 2'd3;
        end else begin
            src_axi_V_last_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        src_axi_V_user_V_0_sel_rd <= 1'b0;
    end else begin
        if (((src_axi_V_user_V_0_ack_out == 1'b1) & (src_axi_V_user_V_0_vld_out == 1'b1))) begin
            src_axi_V_user_V_0_sel_rd <= ~src_axi_V_user_V_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        src_axi_V_user_V_0_sel_wr <= 1'b0;
    end else begin
        if (((src_axi_V_user_V_0_ack_in == 1'b1) & (src_axi_V_user_V_0_vld_in == 1'b1))) begin
            src_axi_V_user_V_0_sel_wr <= ~src_axi_V_user_V_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        src_axi_V_user_V_0_state <= 2'd0;
    end else begin
        if ((((src_axi_V_user_V_0_state == 2'd2) & (src_axi_V_user_V_0_vld_in == 1'b0)) | ((src_axi_V_user_V_0_state == 2'd3) & (src_axi_V_user_V_0_vld_in == 1'b0) & (src_axi_V_user_V_0_ack_out == 1'b1)))) begin
            src_axi_V_user_V_0_state <= 2'd2;
        end else if ((((src_axi_V_user_V_0_state == 2'd1) & (src_axi_V_user_V_0_ack_out == 1'b0)) | ((src_axi_V_user_V_0_state == 2'd3) & (src_axi_V_user_V_0_ack_out == 1'b0) & (src_axi_V_user_V_0_vld_in == 1'b1)))) begin
            src_axi_V_user_V_0_state <= 2'd1;
        end else if (((~((src_axi_V_user_V_0_vld_in == 1'b0) & (src_axi_V_user_V_0_ack_out == 1'b1)) & ~((src_axi_V_user_V_0_ack_out == 1'b0) & (src_axi_V_user_V_0_vld_in == 1'b1)) & (src_axi_V_user_V_0_state == 2'd3)) | ((src_axi_V_user_V_0_state == 2'd1) & (src_axi_V_user_V_0_ack_out == 1'b1)) | ((src_axi_V_user_V_0_state == 2'd2) & (src_axi_V_user_V_0_vld_in == 1'b1)))) begin
            src_axi_V_user_V_0_state <= 2'd3;
        end else begin
            src_axi_V_user_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln24_fu_359_p2 == 1'd0) & (1'd0 == and_ln62_fu_433_p2) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        c_idx_0_reg_244 <= c_idx_fu_365_p2;
    end else if ((~((dst_gray_axi_V_dest_V_1_state == 2'd1) | (dst_gray_axi_V_id_V_1_state == 2'd1) | (dst_gray_axi_V_last_V_1_state == 2'd1) | (dst_gray_axi_V_user_V_1_state == 2'd1) | (dst_gray_axi_V_strb_V_1_state == 2'd1) | (dst_gray_axi_V_keep_V_1_state == 2'd1) | (dst_gray_axi_V_data_V_1_state == 2'd1) | ((dst_gray_axi_V_dest_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_id_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_last_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_user_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_strb_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_keep_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_data_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0))) & (icmp_ln22_fu_347_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        c_idx_0_reg_244 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1003)) begin
        if (((icmp_ln29_fu_397_p2 == 1'd0) & (icmp_ln24_fu_359_p2 == 1'd0))) begin
            p_Val2_s_reg_268 <= src_axi_V_data_V_0_data_out;
        end else if (((icmp_ln29_fu_397_p2 == 1'd1) & (icmp_ln24_fu_359_p2 == 1'd0))) begin
            p_Val2_s_reg_268 <= ap_phi_mux_pixel_in_data_V_1_phi_fu_225_p4;
        end else if ((1'b1 == 1'b1)) begin
            p_Val2_s_reg_268 <= ap_phi_reg_pp1_iter0_p_Val2_s_reg_268;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1003)) begin
        if (((icmp_ln29_fu_397_p2 == 1'd0) & (icmp_ln24_fu_359_p2 == 1'd0))) begin
            pixel_gray_out_last_s_reg_255 <= src_axi_V_last_V_0_data_out;
        end else if (((icmp_ln29_fu_397_p2 == 1'd1) & (icmp_ln24_fu_359_p2 == 1'd0))) begin
            pixel_gray_out_last_s_reg_255 <= ap_phi_mux_pixel_in_last_V_1_phi_fu_214_p4;
        end else if ((1'b1 == 1'b1)) begin
            pixel_gray_out_last_s_reg_255 <= ap_phi_reg_pp1_iter0_pixel_gray_out_last_s_reg_255;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1003)) begin
        if (((icmp_ln29_fu_397_p2 == 1'd0) & (icmp_ln24_fu_359_p2 == 1'd0))) begin
            pixel_gray_out_user_s_reg_280 <= src_axi_V_user_V_0_data_out;
        end else if (((icmp_ln29_fu_397_p2 == 1'd1) & (icmp_ln24_fu_359_p2 == 1'd0))) begin
            pixel_gray_out_user_s_reg_280 <= ap_phi_mux_pixel_in_3_1_phi_fu_236_p4;
        end else if ((1'b1 == 1'b1)) begin
            pixel_gray_out_user_s_reg_280 <= ap_phi_reg_pp1_iter0_pixel_gray_out_user_s_reg_280;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        pixel_in_3_0_reg_187 <= 1'd1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        pixel_in_3_0_reg_187 <= pixel_in_3_3_reg_319;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln24_reg_505 == 1'd0) & (1'd0 == and_ln62_reg_533) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1))) begin
        pixel_in_3_1_reg_233 <= pixel_gray_out_user_s_reg_280;
    end else if ((~((dst_gray_axi_V_dest_V_1_state == 2'd1) | (dst_gray_axi_V_id_V_1_state == 2'd1) | (dst_gray_axi_V_last_V_1_state == 2'd1) | (dst_gray_axi_V_user_V_1_state == 2'd1) | (dst_gray_axi_V_strb_V_1_state == 2'd1) | (dst_gray_axi_V_keep_V_1_state == 2'd1) | (dst_gray_axi_V_data_V_1_state == 2'd1) | ((dst_gray_axi_V_dest_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_id_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_last_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_user_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_strb_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_keep_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_data_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0))) & (icmp_ln22_fu_347_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        pixel_in_3_1_reg_233 <= pixel_in_3_0_reg_187;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp1_stage0_11001)) begin
        if ((1'b1 == ap_condition_1303)) begin
            pixel_in_3_3_reg_319 <= pixel_gray_out_user_s_reg_280_pp1_iter2_reg;
        end else if ((1'b1 == ap_condition_1299)) begin
            pixel_in_3_3_reg_319 <= ap_phi_mux_pixel_in_3_1_phi_fu_236_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        pixel_in_data_V_0_reg_177 <= tmp_data_V_1_reg_483;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        pixel_in_data_V_0_reg_177 <= pixel_in_data_V_3_reg_306;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln24_reg_505 == 1'd0) & (1'd0 == and_ln62_reg_533) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1))) begin
        pixel_in_data_V_1_reg_222 <= p_Val2_s_reg_268;
    end else if ((~((dst_gray_axi_V_dest_V_1_state == 2'd1) | (dst_gray_axi_V_id_V_1_state == 2'd1) | (dst_gray_axi_V_last_V_1_state == 2'd1) | (dst_gray_axi_V_user_V_1_state == 2'd1) | (dst_gray_axi_V_strb_V_1_state == 2'd1) | (dst_gray_axi_V_keep_V_1_state == 2'd1) | (dst_gray_axi_V_data_V_1_state == 2'd1) | ((dst_gray_axi_V_dest_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_id_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_last_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_user_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_strb_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_keep_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_data_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0))) & (icmp_ln22_fu_347_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        pixel_in_data_V_1_reg_222 <= pixel_in_data_V_0_reg_177;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp1_stage0_11001)) begin
        if ((1'b1 == ap_condition_1303)) begin
            pixel_in_data_V_3_reg_306 <= p_Val2_s_reg_268_pp1_iter2_reg;
        end else if ((1'b1 == ap_condition_1299)) begin
            pixel_in_data_V_3_reg_306 <= ap_phi_mux_pixel_in_data_V_1_phi_fu_225_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        pixel_in_last_V_0_reg_167 <= tmp_last_V_1_reg_491;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        pixel_in_last_V_0_reg_167 <= pixel_in_last_V_3_reg_293;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln24_reg_505 == 1'd0) & (1'd0 == and_ln62_reg_533) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1))) begin
        pixel_in_last_V_1_reg_211 <= pixel_gray_out_last_s_reg_255;
    end else if ((~((dst_gray_axi_V_dest_V_1_state == 2'd1) | (dst_gray_axi_V_id_V_1_state == 2'd1) | (dst_gray_axi_V_last_V_1_state == 2'd1) | (dst_gray_axi_V_user_V_1_state == 2'd1) | (dst_gray_axi_V_strb_V_1_state == 2'd1) | (dst_gray_axi_V_keep_V_1_state == 2'd1) | (dst_gray_axi_V_data_V_1_state == 2'd1) | ((dst_gray_axi_V_dest_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_id_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_last_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_user_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_strb_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_keep_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_data_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0))) & (icmp_ln22_fu_347_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        pixel_in_last_V_1_reg_211 <= pixel_in_last_V_0_reg_167;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp1_stage0_11001)) begin
        if ((1'b1 == ap_condition_1303)) begin
            pixel_in_last_V_3_reg_293 <= pixel_gray_out_last_s_reg_255_pp1_iter2_reg;
        end else if ((1'b1 == ap_condition_1299)) begin
            pixel_in_last_V_3_reg_293 <= ap_phi_mux_pixel_in_last_V_1_phi_fu_214_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        r_idx_0_reg_199 <= 9'd0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        r_idx_0_reg_199 <= r_idx_reg_500;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln24_reg_505_pp1_iter1_reg == 1'd0) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        add_ln214_reg_542 <= grp_fu_467_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln24_fu_359_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        and_ln62_reg_533 <= and_ln62_fu_433_p2;
        bit_15_8_V_reg_523 <= {{ap_phi_mux_p_Val2_s_phi_fu_272_p4[15:8]}};
        bit_23_16_V_reg_528 <= {{ap_phi_mux_p_Val2_s_phi_fu_272_p4[23:16]}};
        bit_7_0_V_reg_518 <= bit_7_0_V_fu_403_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        and_ln62_reg_533_pp1_iter1_reg <= and_ln62_reg_533;
        bit_15_8_V_reg_523_pp1_iter1_reg <= bit_15_8_V_reg_523;
        bit_7_0_V_reg_518_pp1_iter1_reg <= bit_7_0_V_reg_518;
        icmp_ln24_reg_505 <= icmp_ln24_fu_359_p2;
        icmp_ln24_reg_505_pp1_iter1_reg <= icmp_ln24_reg_505;
        p_Val2_s_reg_268_pp1_iter1_reg <= p_Val2_s_reg_268;
        pixel_gray_out_last_s_reg_255_pp1_iter1_reg <= pixel_gray_out_last_s_reg_255;
        pixel_gray_out_user_s_reg_280_pp1_iter1_reg <= pixel_gray_out_user_s_reg_280;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp1_stage0_11001)) begin
        and_ln62_reg_533_pp1_iter2_reg <= and_ln62_reg_533_pp1_iter1_reg;
        bit_15_8_V_reg_523_pp1_iter2_reg <= bit_15_8_V_reg_523_pp1_iter1_reg;
        icmp_ln24_reg_505_pp1_iter2_reg <= icmp_ln24_reg_505_pp1_iter1_reg;
        icmp_ln24_reg_505_pp1_iter3_reg <= icmp_ln24_reg_505_pp1_iter2_reg;
        p_Val2_s_reg_268_pp1_iter2_reg <= p_Val2_s_reg_268_pp1_iter1_reg;
        pixel_gray_out_last_s_reg_255_pp1_iter2_reg <= pixel_gray_out_last_s_reg_255_pp1_iter1_reg;
        pixel_gray_out_user_s_reg_280_pp1_iter2_reg <= pixel_gray_out_user_s_reg_280_pp1_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((dst_gray_axi_V_data_V_1_load_A == 1'b1)) begin
        dst_gray_axi_V_data_V_1_payload_A <= {{grp_fu_474_p3[15:8]}};
    end
end

always @ (posedge ap_clk) begin
    if ((dst_gray_axi_V_data_V_1_load_B == 1'b1)) begin
        dst_gray_axi_V_data_V_1_payload_B <= {{grp_fu_474_p3[15:8]}};
    end
end

always @ (posedge ap_clk) begin
    if ((dst_gray_axi_V_last_V_1_load_A == 1'b1)) begin
        dst_gray_axi_V_last_V_1_payload_A <= pixel_gray_out_last_s_reg_255_pp1_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((dst_gray_axi_V_last_V_1_load_B == 1'b1)) begin
        dst_gray_axi_V_last_V_1_payload_B <= pixel_gray_out_last_s_reg_255_pp1_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((dst_gray_axi_V_user_V_1_load_A == 1'b1)) begin
        dst_gray_axi_V_user_V_1_payload_A <= pixel_gray_out_user_s_reg_280_pp1_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((dst_gray_axi_V_user_V_1_load_B == 1'b1)) begin
        dst_gray_axi_V_user_V_1_payload_B <= pixel_gray_out_user_s_reg_280_pp1_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln24_reg_505 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        mul_ln214_reg_537 <= mul_ln214_fu_442_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((dst_gray_axi_V_dest_V_1_state == 2'd1) | (dst_gray_axi_V_id_V_1_state == 2'd1) | (dst_gray_axi_V_last_V_1_state == 2'd1) | (dst_gray_axi_V_user_V_1_state == 2'd1) | (dst_gray_axi_V_strb_V_1_state == 2'd1) | (dst_gray_axi_V_keep_V_1_state == 2'd1) | (dst_gray_axi_V_data_V_1_state == 2'd1) | ((dst_gray_axi_V_dest_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_id_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_last_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_user_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_strb_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_keep_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_data_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0))) & (1'b1 == ap_CS_fsm_state4))) begin
        r_idx_reg_500 <= r_idx_fu_353_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((src_axi_V_data_V_0_load_A == 1'b1)) begin
        src_axi_V_data_V_0_payload_A <= src_axi_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((src_axi_V_data_V_0_load_B == 1'b1)) begin
        src_axi_V_data_V_0_payload_B <= src_axi_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((src_axi_V_last_V_0_load_A == 1'b1)) begin
        src_axi_V_last_V_0_payload_A <= src_axi_TLAST;
    end
end

always @ (posedge ap_clk) begin
    if ((src_axi_V_last_V_0_load_B == 1'b1)) begin
        src_axi_V_last_V_0_payload_B <= src_axi_TLAST;
    end
end

always @ (posedge ap_clk) begin
    if ((src_axi_V_user_V_0_load_A == 1'b1)) begin
        src_axi_V_user_V_0_payload_A <= src_axi_TUSER;
    end
end

always @ (posedge ap_clk) begin
    if ((src_axi_V_user_V_0_load_B == 1'b1)) begin
        src_axi_V_user_V_0_payload_B <= src_axi_TUSER;
    end
end

always @ (posedge ap_clk) begin
    if (((src_axi_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_data_V_1_reg_483 <= src_axi_V_data_V_0_data_out;
        tmp_last_V_1_reg_491 <= src_axi_V_last_V_0_data_out;
    end
end

always @ (*) begin
    if ((~((dst_gray_axi_V_dest_V_1_state == 2'd1) | (dst_gray_axi_V_id_V_1_state == 2'd1) | (dst_gray_axi_V_last_V_1_state == 2'd1) | (dst_gray_axi_V_user_V_1_state == 2'd1) | (dst_gray_axi_V_strb_V_1_state == 2'd1) | (dst_gray_axi_V_keep_V_1_state == 2'd1) | (dst_gray_axi_V_data_V_1_state == 2'd1) | ((dst_gray_axi_V_dest_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_id_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_last_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_user_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_strb_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_keep_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_data_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0))) & (icmp_ln22_fu_347_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter4 == 1'b0) & (ap_enable_reg_pp1_iter3 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter2 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1294)) begin
        if ((icmp_ln29_fu_397_p2 == 1'd0)) begin
            ap_phi_mux_p_Val2_s_phi_fu_272_p4 = src_axi_V_data_V_0_data_out;
        end else if ((icmp_ln29_fu_397_p2 == 1'd1)) begin
            ap_phi_mux_p_Val2_s_phi_fu_272_p4 = ap_phi_mux_pixel_in_data_V_1_phi_fu_225_p4;
        end else begin
            ap_phi_mux_p_Val2_s_phi_fu_272_p4 = ap_phi_reg_pp1_iter0_p_Val2_s_reg_268;
        end
    end else begin
        ap_phi_mux_p_Val2_s_phi_fu_272_p4 = ap_phi_reg_pp1_iter0_p_Val2_s_reg_268;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1294)) begin
        if ((icmp_ln29_fu_397_p2 == 1'd0)) begin
            ap_phi_mux_pixel_gray_out_last_s_phi_fu_260_p4 = src_axi_V_last_V_0_data_out;
        end else if ((icmp_ln29_fu_397_p2 == 1'd1)) begin
            ap_phi_mux_pixel_gray_out_last_s_phi_fu_260_p4 = ap_phi_mux_pixel_in_last_V_1_phi_fu_214_p4;
        end else begin
            ap_phi_mux_pixel_gray_out_last_s_phi_fu_260_p4 = ap_phi_reg_pp1_iter0_pixel_gray_out_last_s_reg_255;
        end
    end else begin
        ap_phi_mux_pixel_gray_out_last_s_phi_fu_260_p4 = ap_phi_reg_pp1_iter0_pixel_gray_out_last_s_reg_255;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (icmp_ln24_reg_505 == 1'd0) & (1'd0 == and_ln62_reg_533) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1))) begin
        ap_phi_mux_pixel_in_3_1_phi_fu_236_p4 = pixel_gray_out_user_s_reg_280;
    end else begin
        ap_phi_mux_pixel_in_3_1_phi_fu_236_p4 = pixel_in_3_1_reg_233;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (icmp_ln24_reg_505 == 1'd0) & (1'd0 == and_ln62_reg_533) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1))) begin
        ap_phi_mux_pixel_in_data_V_1_phi_fu_225_p4 = p_Val2_s_reg_268;
    end else begin
        ap_phi_mux_pixel_in_data_V_1_phi_fu_225_p4 = pixel_in_data_V_1_reg_222;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (icmp_ln24_reg_505 == 1'd0) & (1'd0 == and_ln62_reg_533) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1))) begin
        ap_phi_mux_pixel_in_last_V_1_phi_fu_214_p4 = pixel_gray_out_last_s_reg_255;
    end else begin
        ap_phi_mux_pixel_in_last_V_1_phi_fu_214_p4 = pixel_in_last_V_1_reg_211;
    end
end

always @ (*) begin
    if ((~((dst_gray_axi_V_dest_V_1_state == 2'd1) | (dst_gray_axi_V_id_V_1_state == 2'd1) | (dst_gray_axi_V_last_V_1_state == 2'd1) | (dst_gray_axi_V_user_V_1_state == 2'd1) | (dst_gray_axi_V_strb_V_1_state == 2'd1) | (dst_gray_axi_V_keep_V_1_state == 2'd1) | (dst_gray_axi_V_data_V_1_state == 2'd1) | ((dst_gray_axi_V_dest_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_id_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_last_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_user_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_strb_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_keep_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_data_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0))) & (icmp_ln22_fu_347_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp1_stage0) & (icmp_ln24_reg_505_pp1_iter3_reg == 1'd0) & (ap_enable_reg_pp1_iter4 == 1'b1)) | ((1'b0 == ap_block_pp1_stage0) & (icmp_ln24_reg_505_pp1_iter2_reg == 1'd0) & (ap_enable_reg_pp1_iter3 == 1'b1)))) begin
        dst_gray_axi_TDATA_blk_n = dst_gray_axi_V_data_V_1_state[1'd1];
    end else begin
        dst_gray_axi_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((dst_gray_axi_V_data_V_1_sel == 1'b1)) begin
        dst_gray_axi_V_data_V_1_data_out = dst_gray_axi_V_data_V_1_payload_B;
    end else begin
        dst_gray_axi_V_data_V_1_data_out = dst_gray_axi_V_data_V_1_payload_A;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln24_reg_505_pp1_iter2_reg == 1'd0) & (ap_enable_reg_pp1_iter3 == 1'b1))) begin
        dst_gray_axi_V_data_V_1_vld_in = 1'b1;
    end else begin
        dst_gray_axi_V_data_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln24_reg_505_pp1_iter2_reg == 1'd0) & (ap_enable_reg_pp1_iter3 == 1'b1))) begin
        dst_gray_axi_V_dest_V_1_vld_in = 1'b1;
    end else begin
        dst_gray_axi_V_dest_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln24_reg_505_pp1_iter2_reg == 1'd0) & (ap_enable_reg_pp1_iter3 == 1'b1))) begin
        dst_gray_axi_V_id_V_1_vld_in = 1'b1;
    end else begin
        dst_gray_axi_V_id_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln24_reg_505_pp1_iter2_reg == 1'd0) & (ap_enable_reg_pp1_iter3 == 1'b1))) begin
        dst_gray_axi_V_keep_V_1_vld_in = 1'b1;
    end else begin
        dst_gray_axi_V_keep_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((dst_gray_axi_V_last_V_1_sel == 1'b1)) begin
        dst_gray_axi_V_last_V_1_data_out = dst_gray_axi_V_last_V_1_payload_B;
    end else begin
        dst_gray_axi_V_last_V_1_data_out = dst_gray_axi_V_last_V_1_payload_A;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln24_reg_505_pp1_iter2_reg == 1'd0) & (ap_enable_reg_pp1_iter3 == 1'b1))) begin
        dst_gray_axi_V_last_V_1_vld_in = 1'b1;
    end else begin
        dst_gray_axi_V_last_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln24_reg_505_pp1_iter2_reg == 1'd0) & (ap_enable_reg_pp1_iter3 == 1'b1))) begin
        dst_gray_axi_V_strb_V_1_vld_in = 1'b1;
    end else begin
        dst_gray_axi_V_strb_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((dst_gray_axi_V_user_V_1_sel == 1'b1)) begin
        dst_gray_axi_V_user_V_1_data_out = dst_gray_axi_V_user_V_1_payload_B;
    end else begin
        dst_gray_axi_V_user_V_1_data_out = dst_gray_axi_V_user_V_1_payload_A;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln24_reg_505_pp1_iter2_reg == 1'd0) & (ap_enable_reg_pp1_iter3 == 1'b1))) begin
        dst_gray_axi_V_user_V_1_vld_in = 1'b1;
    end else begin
        dst_gray_axi_V_user_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b0 == ap_block_pp1_stage0) & (icmp_ln29_fu_397_p2 == 1'd0) & (icmp_ln24_fu_359_p2 == 1'd0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)))) begin
        src_axi_TDATA_blk_n = src_axi_V_data_V_0_state[1'd0];
    end else begin
        src_axi_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp1_stage0_11001) & (ap_predicate_op65_read_state5 == 1'b1) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((src_axi_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        src_axi_V_data_V_0_ack_out = 1'b1;
    end else begin
        src_axi_V_data_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((src_axi_V_data_V_0_sel == 1'b1)) begin
        src_axi_V_data_V_0_data_out = src_axi_V_data_V_0_payload_B;
    end else begin
        src_axi_V_data_V_0_data_out = src_axi_V_data_V_0_payload_A;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp1_stage0_11001) & (ap_predicate_op65_read_state5 == 1'b1) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((src_axi_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        src_axi_V_dest_V_0_ack_out = 1'b1;
    end else begin
        src_axi_V_dest_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp1_stage0_11001) & (ap_predicate_op65_read_state5 == 1'b1) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((src_axi_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        src_axi_V_last_V_0_ack_out = 1'b1;
    end else begin
        src_axi_V_last_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((src_axi_V_last_V_0_sel == 1'b1)) begin
        src_axi_V_last_V_0_data_out = src_axi_V_last_V_0_payload_B;
    end else begin
        src_axi_V_last_V_0_data_out = src_axi_V_last_V_0_payload_A;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp1_stage0_11001) & (ap_predicate_op65_read_state5 == 1'b1) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((src_axi_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        src_axi_V_user_V_0_ack_out = 1'b1;
    end else begin
        src_axi_V_user_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((src_axi_V_user_V_0_sel == 1'b1)) begin
        src_axi_V_user_V_0_data_out = src_axi_V_user_V_0_payload_B;
    end else begin
        src_axi_V_user_V_0_data_out = src_axi_V_user_V_0_payload_A;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_fu_337_p1 == 1'd0) & (src_axi_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if (((grp_fu_337_p1 == 1'd1) & (src_axi_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if ((~((dst_gray_axi_V_dest_V_1_state == 2'd1) | (dst_gray_axi_V_id_V_1_state == 2'd1) | (dst_gray_axi_V_last_V_1_state == 2'd1) | (dst_gray_axi_V_user_V_1_state == 2'd1) | (dst_gray_axi_V_strb_V_1_state == 2'd1) | (dst_gray_axi_V_keep_V_1_state == 2'd1) | (dst_gray_axi_V_data_V_1_state == 2'd1) | ((dst_gray_axi_V_dest_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_id_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_last_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_user_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_strb_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_keep_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_data_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0))) & (icmp_ln22_fu_347_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if ((~((dst_gray_axi_V_dest_V_1_state == 2'd1) | (dst_gray_axi_V_id_V_1_state == 2'd1) | (dst_gray_axi_V_last_V_1_state == 2'd1) | (dst_gray_axi_V_user_V_1_state == 2'd1) | (dst_gray_axi_V_strb_V_1_state == 2'd1) | (dst_gray_axi_V_keep_V_1_state == 2'd1) | (dst_gray_axi_V_data_V_1_state == 2'd1) | ((dst_gray_axi_V_dest_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_id_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_last_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_user_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_strb_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_keep_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_data_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0))) & (icmp_ln22_fu_347_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_pp1_stage0 : begin
            if (~((ap_enable_reg_pp1_iter3 == 1'b0) & (ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if (((ap_enable_reg_pp1_iter3 == 1'b0) & (ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign and_ln62_fu_433_p2 = (icmp_ln62_fu_427_p2 & ap_phi_mux_pixel_gray_out_last_s_phi_fu_260_p4);

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp1_stage0_01001 = ((src_axi_V_data_V_0_vld_out == 1'b0) & (ap_predicate_op65_read_state5 == 1'b1) & (ap_enable_reg_pp1_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp1_stage0_11001 = (((1'b1 == ap_block_state9_io) & (ap_enable_reg_pp1_iter4 == 1'b1)) | ((1'b1 == ap_block_state8_io) & (ap_enable_reg_pp1_iter3 == 1'b1)) | ((src_axi_V_data_V_0_vld_out == 1'b0) & (ap_predicate_op65_read_state5 == 1'b1) & (ap_enable_reg_pp1_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp1_stage0_subdone = (((1'b1 == ap_block_state9_io) & (ap_enable_reg_pp1_iter4 == 1'b1)) | ((1'b1 == ap_block_state8_io) & (ap_enable_reg_pp1_iter3 == 1'b1)) | ((src_axi_V_data_V_0_vld_out == 1'b0) & (ap_predicate_op65_read_state5 == 1'b1) & (ap_enable_reg_pp1_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_state4 = ((dst_gray_axi_V_dest_V_1_state == 2'd1) | (dst_gray_axi_V_id_V_1_state == 2'd1) | (dst_gray_axi_V_last_V_1_state == 2'd1) | (dst_gray_axi_V_user_V_1_state == 2'd1) | (dst_gray_axi_V_strb_V_1_state == 2'd1) | (dst_gray_axi_V_keep_V_1_state == 2'd1) | (dst_gray_axi_V_data_V_1_state == 2'd1) | ((dst_gray_axi_V_dest_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_id_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_last_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_user_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_strb_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_keep_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)) | ((dst_gray_axi_V_data_V_1_state == 2'd3) & (dst_gray_axi_TREADY == 1'b0)));
end

always @ (*) begin
    ap_block_state5_pp1_stage0_iter0 = ((src_axi_V_data_V_0_vld_out == 1'b0) & (ap_predicate_op65_read_state5 == 1'b1));
end

assign ap_block_state6_pp1_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp1_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state8_io = ((icmp_ln24_reg_505_pp1_iter2_reg == 1'd0) & (dst_gray_axi_V_data_V_1_ack_in == 1'b0));
end

assign ap_block_state8_pp1_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state9_io = ((icmp_ln24_reg_505_pp1_iter3_reg == 1'd0) & (dst_gray_axi_V_data_V_1_ack_in == 1'b0));
end

assign ap_block_state9_pp1_stage0_iter4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_1003 = ((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0));
end

always @ (*) begin
    ap_condition_1294 = ((1'b0 == ap_block_pp1_stage0) & (icmp_ln24_fu_359_p2 == 1'd0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0));
end

always @ (*) begin
    ap_condition_1299 = ((icmp_ln24_fu_359_p2 == 1'd1) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0));
end

always @ (*) begin
    ap_condition_1303 = ((1'd1 == and_ln62_reg_533_pp1_iter2_reg) & (icmp_ln24_reg_505_pp1_iter2_reg == 1'd0) & (ap_enable_reg_pp1_iter3 == 1'b1));
end

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign ap_phi_reg_pp1_iter0_p_Val2_s_reg_268 = 'bx;

assign ap_phi_reg_pp1_iter0_pixel_gray_out_last_s_reg_255 = 'bx;

assign ap_phi_reg_pp1_iter0_pixel_gray_out_user_s_reg_280 = 'bx;

always @ (*) begin
    ap_predicate_op65_read_state5 = ((icmp_ln29_fu_397_p2 == 1'd0) & (icmp_ln24_fu_359_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_tran9to10_state5 = ((icmp_ln24_fu_359_p2 == 1'd1) | (1'd1 == and_ln62_fu_433_p2));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign bit_7_0_V_fu_403_p1 = ap_phi_mux_p_Val2_s_phi_fu_272_p4[7:0];

assign c_idx_fu_365_p2 = (c_idx_0_reg_244 + 10'd1);

assign dst_gray_axi_TDATA = dst_gray_axi_V_data_V_1_data_out;

assign dst_gray_axi_TDEST = dst_gray_axi_V_dest_V_1_data_out;

assign dst_gray_axi_TID = dst_gray_axi_V_id_V_1_data_out;

assign dst_gray_axi_TKEEP = dst_gray_axi_V_keep_V_1_data_out;

assign dst_gray_axi_TLAST = dst_gray_axi_V_last_V_1_data_out;

assign dst_gray_axi_TSTRB = dst_gray_axi_V_strb_V_1_data_out;

assign dst_gray_axi_TUSER = dst_gray_axi_V_user_V_1_data_out;

assign dst_gray_axi_TVALID = dst_gray_axi_V_dest_V_1_state[1'd0];

assign dst_gray_axi_V_data_V_1_ack_in = dst_gray_axi_V_data_V_1_state[1'd1];

assign dst_gray_axi_V_data_V_1_ack_out = dst_gray_axi_TREADY;

assign dst_gray_axi_V_data_V_1_load_A = (~dst_gray_axi_V_data_V_1_sel_wr & dst_gray_axi_V_data_V_1_state_cmp_full);

assign dst_gray_axi_V_data_V_1_load_B = (dst_gray_axi_V_data_V_1_state_cmp_full & dst_gray_axi_V_data_V_1_sel_wr);

assign dst_gray_axi_V_data_V_1_sel = dst_gray_axi_V_data_V_1_sel_rd;

assign dst_gray_axi_V_data_V_1_state_cmp_full = ((dst_gray_axi_V_data_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign dst_gray_axi_V_data_V_1_vld_out = dst_gray_axi_V_data_V_1_state[1'd0];

assign dst_gray_axi_V_dest_V_1_ack_out = dst_gray_axi_TREADY;

assign dst_gray_axi_V_dest_V_1_data_out = 1'd0;

assign dst_gray_axi_V_dest_V_1_sel = dst_gray_axi_V_dest_V_1_sel_rd;

assign dst_gray_axi_V_dest_V_1_vld_out = dst_gray_axi_V_dest_V_1_state[1'd0];

assign dst_gray_axi_V_id_V_1_ack_out = dst_gray_axi_TREADY;

assign dst_gray_axi_V_id_V_1_data_out = 1'd0;

assign dst_gray_axi_V_id_V_1_sel = dst_gray_axi_V_id_V_1_sel_rd;

assign dst_gray_axi_V_id_V_1_vld_out = dst_gray_axi_V_id_V_1_state[1'd0];

assign dst_gray_axi_V_keep_V_1_ack_out = dst_gray_axi_TREADY;

assign dst_gray_axi_V_keep_V_1_data_out = 1'd1;

assign dst_gray_axi_V_keep_V_1_sel = dst_gray_axi_V_keep_V_1_sel_rd;

assign dst_gray_axi_V_keep_V_1_vld_out = dst_gray_axi_V_keep_V_1_state[1'd0];

assign dst_gray_axi_V_last_V_1_ack_in = dst_gray_axi_V_last_V_1_state[1'd1];

assign dst_gray_axi_V_last_V_1_ack_out = dst_gray_axi_TREADY;

assign dst_gray_axi_V_last_V_1_load_A = (~dst_gray_axi_V_last_V_1_sel_wr & dst_gray_axi_V_last_V_1_state_cmp_full);

assign dst_gray_axi_V_last_V_1_load_B = (dst_gray_axi_V_last_V_1_state_cmp_full & dst_gray_axi_V_last_V_1_sel_wr);

assign dst_gray_axi_V_last_V_1_sel = dst_gray_axi_V_last_V_1_sel_rd;

assign dst_gray_axi_V_last_V_1_state_cmp_full = ((dst_gray_axi_V_last_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign dst_gray_axi_V_last_V_1_vld_out = dst_gray_axi_V_last_V_1_state[1'd0];

assign dst_gray_axi_V_strb_V_1_ack_out = dst_gray_axi_TREADY;

assign dst_gray_axi_V_strb_V_1_data_out = 1'd1;

assign dst_gray_axi_V_strb_V_1_sel = dst_gray_axi_V_strb_V_1_sel_rd;

assign dst_gray_axi_V_strb_V_1_vld_out = dst_gray_axi_V_strb_V_1_state[1'd0];

assign dst_gray_axi_V_user_V_1_ack_in = dst_gray_axi_V_user_V_1_state[1'd1];

assign dst_gray_axi_V_user_V_1_ack_out = dst_gray_axi_TREADY;

assign dst_gray_axi_V_user_V_1_load_A = (~dst_gray_axi_V_user_V_1_sel_wr & dst_gray_axi_V_user_V_1_state_cmp_full);

assign dst_gray_axi_V_user_V_1_load_B = (dst_gray_axi_V_user_V_1_state_cmp_full & dst_gray_axi_V_user_V_1_sel_wr);

assign dst_gray_axi_V_user_V_1_sel = dst_gray_axi_V_user_V_1_sel_rd;

assign dst_gray_axi_V_user_V_1_state_cmp_full = ((dst_gray_axi_V_user_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign dst_gray_axi_V_user_V_1_vld_out = dst_gray_axi_V_user_V_1_state[1'd0];

assign grp_fu_337_p1 = src_axi_V_user_V_0_data_out;

assign grp_fu_467_p0 = 14'd29;

assign grp_fu_467_p1 = grp_fu_467_p10;

assign grp_fu_467_p10 = bit_7_0_V_reg_518_pp1_iter1_reg;

assign grp_fu_474_p0 = 16'd150;

assign grp_fu_474_p1 = grp_fu_474_p10;

assign grp_fu_474_p10 = bit_15_8_V_reg_523_pp1_iter2_reg;

assign grp_fu_474_p2 = grp_fu_474_p20;

assign grp_fu_474_p20 = add_ln214_reg_542;

assign icmp_ln22_fu_347_p2 = ((r_idx_0_reg_199 == 9'd480) ? 1'b1 : 1'b0);

assign icmp_ln24_fu_359_p2 = ((c_idx_0_reg_244 == 10'd640) ? 1'b1 : 1'b0);

assign icmp_ln29_fu_397_p2 = ((or_ln_fu_389_p3 == 10'd0) ? 1'b1 : 1'b0);

assign icmp_ln62_fu_427_p2 = ((c_idx_0_reg_244 != 10'd639) ? 1'b1 : 1'b0);

assign mul_ln214_fu_442_p1 = mul_ln214_fu_442_p10;

assign mul_ln214_fu_442_p10 = bit_23_16_V_reg_528;

assign mul_ln214_fu_442_p2 = (15'd77 * mul_ln214_fu_442_p1);

assign or_ln29_fu_375_p2 = (trunc_ln29_fu_371_p1 | r_idx_0_reg_199);

assign or_ln_fu_389_p3 = {{tmp_3_fu_381_p3}, {or_ln29_fu_375_p2}};

assign r_idx_fu_353_p2 = (r_idx_0_reg_199 + 9'd1);

assign src_axi_TREADY = src_axi_V_dest_V_0_state[1'd1];

assign src_axi_V_data_V_0_ack_in = src_axi_V_data_V_0_state[1'd1];

assign src_axi_V_data_V_0_load_A = (src_axi_V_data_V_0_state_cmp_full & ~src_axi_V_data_V_0_sel_wr);

assign src_axi_V_data_V_0_load_B = (src_axi_V_data_V_0_state_cmp_full & src_axi_V_data_V_0_sel_wr);

assign src_axi_V_data_V_0_sel = src_axi_V_data_V_0_sel_rd;

assign src_axi_V_data_V_0_state_cmp_full = ((src_axi_V_data_V_0_state != 2'd1) ? 1'b1 : 1'b0);

assign src_axi_V_data_V_0_vld_in = src_axi_TVALID;

assign src_axi_V_data_V_0_vld_out = src_axi_V_data_V_0_state[1'd0];

assign src_axi_V_dest_V_0_vld_in = src_axi_TVALID;

assign src_axi_V_last_V_0_ack_in = src_axi_V_last_V_0_state[1'd1];

assign src_axi_V_last_V_0_load_A = (src_axi_V_last_V_0_state_cmp_full & ~src_axi_V_last_V_0_sel_wr);

assign src_axi_V_last_V_0_load_B = (src_axi_V_last_V_0_state_cmp_full & src_axi_V_last_V_0_sel_wr);

assign src_axi_V_last_V_0_sel = src_axi_V_last_V_0_sel_rd;

assign src_axi_V_last_V_0_state_cmp_full = ((src_axi_V_last_V_0_state != 2'd1) ? 1'b1 : 1'b0);

assign src_axi_V_last_V_0_vld_in = src_axi_TVALID;

assign src_axi_V_last_V_0_vld_out = src_axi_V_last_V_0_state[1'd0];

assign src_axi_V_user_V_0_ack_in = src_axi_V_user_V_0_state[1'd1];

assign src_axi_V_user_V_0_load_A = (src_axi_V_user_V_0_state_cmp_full & ~src_axi_V_user_V_0_sel_wr);

assign src_axi_V_user_V_0_load_B = (src_axi_V_user_V_0_state_cmp_full & src_axi_V_user_V_0_sel_wr);

assign src_axi_V_user_V_0_sel = src_axi_V_user_V_0_sel_rd;

assign src_axi_V_user_V_0_state_cmp_full = ((src_axi_V_user_V_0_state != 2'd1) ? 1'b1 : 1'b0);

assign src_axi_V_user_V_0_vld_in = src_axi_TVALID;

assign src_axi_V_user_V_0_vld_out = src_axi_V_user_V_0_state[1'd0];

assign tmp_3_fu_381_p3 = c_idx_0_reg_244[32'd9];

assign trunc_ln29_fu_371_p1 = c_idx_0_reg_244[8:0];

endmodule //rgb2gray
